name: Weekly Google Trends Scraper

on:
  schedule:
    - cron: '30 0 * * 1'  # Every Monday at 00:30 UTC
  workflow_dispatch:      # Optional: allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Google Trends Script
        run: python trend_scraper.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trend-csv
          path: output/travel_insurance_trend.csv
