name: Weekly Google Trends Scraper (Travel Insurance)

on:
  schedule:
    - cron: '30 0 * * 1'  # Every Monday at 00:30 UTC
  workflow_dispatch:      # Optional: allows manual triggering

concurrency:
  group: google-trends-scraper
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Random backoff before start
        run: |
          python - <<'PY'
          import random, time
          t = random.randint(20, 180)
          print(f"Sleeping {t}s to avoid rate limits")
          time.sleep(t)
          PY

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade git+https://github.com/GeneralMills/pytrends
          pip install -r requirements.txt
          python - <<'PY'
          import pytrends, urllib3
          print("pytrends:", getattr(pytrends, "__version__", "unknown"))
          print("urllib3:", urllib3.__version__)
          PY


      - name: Run Google Trends Script
        run: python trend_scraper.py

      - name: Commit CSV to docs folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "Jake Osmond (GitHub Actions)"
          git config --global user.email "github-actions@github.com"
          git add docs/travel_insurance_trend.csv
          git commit -m "Update CSV with weekly trends" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push origin HEAD:main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: trend-csv
          path: docs/travel_insurance_trend.csv
